name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets.
version: 1.0.0
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=2.2.2 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  chewie: ^0.9.10
  chewie_audio: ^1.0.0+1
  css_colors: ^1.0.2
  csslib: ^0.16.1
  fancy_shimmer_image: ^1.2.0
  flutter_svg: ^0.17.4
  html: ^0.14.0+3
  video_player: ^0.10.10
  webview_flutter: ^0.3.21

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
